name: Node CI

on:
  pull_request: {}
  push:
    branches-ignore:
      - tmp

jobs:
  build:
    name: Node CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Run Tests with Coverage
        run: npm run test:cover