name: Node CI

on:
  pull_request: {}
  push:
    branches-ignore:
      - tmp

jobs:
  build:
    name: Node CI

    runs-on: ubuntu-latest

    env:
      REPORT_COVERAGE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Build Package
        run: npm run build
      
      - name: Run Tests with Coverage
        run: npm run test:cover

      - name: Report Coverage to Codecov
        if: ${{ env.REPORT_COVERAGE == true }}
        uses: codecov/codecov-action@v1